import localFont from 'next/font/local';
import './styles/main.scss';
import Header from './components/shared/header/Header';
import Footer from './components/shared/footer/Footer';
const geistSans = localFont({
  src: [
    {
      path: './fonts/AV-Fontimer.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/AV-Fontimer-Black.woff',
      weight: '900',
      style: 'normal',
    },
    {
      path: './fonts/AV-Fontimer-ExtBd.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/AV-Fontimer-SemBd.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/AV-Fontimer-Med.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/AV-Fontimer-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/AV-Fontimer-ExtBd.woff',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/AV-Fontimer-ExtLt.woff',
      weight: '200',
      style: 'normal',
    },
  ],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={geistSans.className}>
        <Header />
        <div className="wrapper">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
